version: '2'

networks:
  sql-cluster:
    driver: bridge
  sql:
    driver: bridge

services:
  mysql-proxy-1:
    container_name: mysql-proxy-1
    build: ./haproxy
    ports:
      - 3306:3306
      - 1936:1936
    networks:
      - sql
      - sql-cluster
    depends_on:
      - mysql-node-1
      - mysql-node-2
      - mysql-node-3


  mysql-node-1:
    container_name: mysql-node-1
    build: ./mariadb
    networks:
      - sql-cluster
    environment:
      - MODE=BOOT
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=test
      - HAPROXY_USER=haproxy_check
      - GALERA=On
      - REPLICATION_PASSWORD=test
      - NODE_NAME=mysql-node-1
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://
    command: --wsrep-new-cluster

  mysql-node-2:
    container_name: mysql-node-2
    build: ./mariadb
    networks:
      - sql-cluster
    environment:
      - GALERA=On
      - REPLICATION_PASSWORD=test
      - NODE_NAME=mysql-node-2
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://mysql-node-1
      
  mysql-node-3:
    container_name: mysql-node-3
    build: ./mariadb
    networks:
      - sql-cluster
    environment:
      - GALERA=On
      - REPLICATION_PASSWORD=test
      - NODE_NAME=mysql-node-3
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://mysql-node-1
      